# Generated by Django 6.0.5 on 2026-06-04 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_recurring_trip_passenger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring_trip',
            name='passenger',
        ),
        migrations.AddField(
            model_name='recurring_trip',
            name='passenger',
            field=models.ManyToManyField(related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
