# Generated by Django 6.0.5 on 2026-06-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_recurring_trip_passenger_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
