# Generated by Django 6.0.5 on 2026-06-08 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_remove_recurring_trip_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_trip',
            name='arrives',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='time car arrives'),
        ),
        migrations.AddField(
            model_name='recurring_trip',
            name='leaves',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='time car leaves'),
        ),
        migrations.AlterField(
            model_name='recurring_trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
    ]
