# Generated by Django 6.0.5 on 2026-06-08 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_recurring_trip_arrives_recurring_trip_leaves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_trip',
            name='leaves',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='time car leaves'),
        ),
    ]
