# Generated by Django 6.0.5 on 2026-06-08 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_recurring_trip_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_trip',
            name='leaves',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 0), verbose_name='time car leaves'),
        ),
    ]
