# Generated by Django 6.0.5 on 2026-06-08 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_alter_recurring_trip_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_trip',
            name='arrives',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='time car arrives'),
        ),
    ]
