# Generated by Django 6.0.5 on 2026-06-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_alter_recurring_trip_arrives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_trip',
            name='arrives',
            field=models.DateTimeField(verbose_name='time car arrives'),
        ),
        migrations.AlterField(
            model_name='recurring_trip',
            name='leaves',
            field=models.DateTimeField(verbose_name='time car leaves'),
        ),
    ]
