# Generated by Django 6.0.5 on 2026-06-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_alter_recurring_trip_arrives_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurring_trip',
            old_name='arrives',
            new_name='arriving_at',
        ),
        migrations.RenameField(
            model_name='recurring_trip',
            old_name='leaves',
            new_name='leaving_at',
        ),
    ]
