# Generated by Django 6.0.5 on 2026-06-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_rename_arrives_recurring_trip_arriving_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_trip',
            name='note',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
