# Generated by Django 6.0.5 on 2026-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_recurring_trip_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_trip',
            name='note',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
