# Generated by Django 6.0.5 on 2026-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_alter_recurring_trip_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_trip',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Any kind of note for passengers'),
        ),
    ]
