# Generated by Django 6.0.5 on 2026-06-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_alter_recurring_trip_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring_trip',
            name='arriving_at',
        ),
        migrations.RemoveField(
            model_name='recurring_trip',
            name='leaving_at',
        ),
        migrations.AddField(
            model_name='recurring_trip',
            name='arriving_at_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurring_trip',
            name='arriving_at_minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurring_trip',
            name='arriving_at_weekday',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurring_trip',
            name='leaving_at_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurring_trip',
            name='leaving_at_minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurring_trip',
            name='leaving_at_weekday',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
            preserve_default=False,
        ),
    ]
