# Generated by Django 6.0.5 on 2026-06-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_remove_recurring_trip_arriving_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_trip',
            name='max_passengers',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
