# Generated by Django 6.0.5 on 2026-06-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_alter_recurring_trip_arriving_at_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_trip',
            name='destName',
            field=models.CharField(default='LUT Lahti', help_text='Destination name'),
            preserve_default=False,
        ),
    ]
