# Generated by Django 6.0.5 on 2026-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_recurring_trip_destname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_trip',
            name='arriving_at_weekday',
            field=models.CharField(choices=[('Monday', 'monday'), ('Tuesday', 'tuesday'), ('Wednesday', 'wednesday'), ('Thursday', 'thursday'), ('Friday', 'friday'), ('Saturday', 'saturday'), ('Sunday', 'sunday'), ('Weekdays', 'weekdays'), ('Weekends', 'weekends')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recurring_trip',
            name='leaving_at_weekday',
            field=models.CharField(choices=[('Monday', 'monday'), ('Tuesday', 'tuesday'), ('Wednesday', 'wednesday'), ('Thursday', 'thursday'), ('Friday', 'friday'), ('Saturday', 'saturday'), ('Sunday', 'sunday'), ('Weekdays', 'weekdays'), ('Weekends', 'weekends')], max_length=10),
        ),
    ]
