# Generated by Django 5.2.16 on 2026-07-07 19:39

import django_geoaddress.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0020_alter_recurring_trip_arriving_at_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_trip',
            name='test',
            field=django_geoaddress.fields.GeoaddressField(default='Test Address 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recurring_trip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
