# Generated by Django 5.2.16 on 2026-07-25 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_recurring_trips_user_rides'),
        ('test_app', '0021_recurring_trip_test_alter_address_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recurring_Trip',
            new_name='Ride',
        ),
    ]
