# Generated by Django 5.2.16 on 2026-07-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0023_rename_destname_ride_dest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='test',
        ),
    ]
