# Generated by Django 5.2.16 on 2026-08-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0024_remove_ride_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='fr_arriving_at_time',
            new_name='friday_arriving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='fr_leaving_at_time',
            new_name='friday_leaving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='mo_arriving_at_time',
            new_name='monday_arriving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='mo_leaving_at_time',
            new_name='monday_leaving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='sa_arriving_at_time',
            new_name='saturday_arriving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='sa_leaving_at_time',
            new_name='saturday_leaving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='su_arriving_at_time',
            new_name='sunday_arriving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='su_leaving_at_time',
            new_name='sunday_leaving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='th_arriving_at_time',
            new_name='thursday_arriving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='th_leaving_at_time',
            new_name='thursday_leaving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='tu_arriving_at_time',
            new_name='tuesday_arriving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='tu_leaving_at_time',
            new_name='tuesday_leaving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='we_arriving_at_time',
            new_name='wednesday_arriving_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='we_leaving_at_time',
            new_name='wednesday_leaving_at_time',
        ),
    ]
