# Generated by Django 5.2.16 on 2026-08-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0025_rename_fr_arriving_at_time_ride_friday_arriving_at_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='friday_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='monday_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='saturday_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='sunday_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='thursday_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='tuesday_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='wednesday_check',
            field=models.BooleanField(default=False),
        ),
    ]
