# Generated by Django 5.2.16 on 2026-08-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0026_ride_friday_check_ride_monday_check_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='arriving_at_date',
            new_name='arriving_at_date_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='arriving_at_time',
            new_name='leaving_at_date_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='leaving_at_date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='leaving_at_time',
        ),
    ]
