# Generated by Django 5.2.16 on 2026-08-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0027_rename_arriving_at_date_ride_arriving_at_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='friday_arriving_at_time',
            new_name='friday_returning_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='monday_arriving_at_time',
            new_name='monday_returning_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='arriving_at_date_time',
            new_name='returning_at_date_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='saturday_arriving_at_time',
            new_name='saturday_returning_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='sunday_arriving_at_time',
            new_name='sunday_returning_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='thursday_arriving_at_time',
            new_name='thursday_returning_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='tuesday_arriving_at_time',
            new_name='tuesday_returning_at_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='wednesday_arriving_at_time',
            new_name='wednesday_returning_at_time',
        ),
    ]
