# Generated by Django 5.2.16 on 2026-08-07 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0028_rename_friday_arriving_at_time_ride_friday_returning_at_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passenger',
            field=models.ManyToManyField(blank=True, null=True, related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
