# Generated by Django 5.2.16 on 2026-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0029_alter_ride_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='max_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
