# Generated by Django 5.2.16 on 2026-09-27 20:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0030_alter_ride_max_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination_json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='start_json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='vias_json',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True), blank=True, null=True, size=None),
        ),
    ]
