# Generated by Django 5.2.16 on 2026-09-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0031_ride_destination_json_ride_start_json_ride_vias_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dest_name',
            field=models.CharField(blank=True, help_text='Destination name', null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start',
            field=models.CharField(blank=True, null=True),
        ),
    ]
