# Generated by Django 5.2.16 on 2026-09-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0032_alter_ride_dest_name_alter_ride_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination_json',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_json',
            field=models.CharField(),
        ),
    ]
