# Generated by Django 5.2.16 on 2026-09-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0033_alter_ride_destination_json_alter_ride_start_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_json',
            field=models.JSONField(),
        ),
    ]
