# Generated by Django 5.2.16 on 2026-09-28 13:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0034_alter_ride_destination_json_alter_ride_start_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, geography=True, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='start_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
