# Generated by Django 5.2.16 on 2026-09-28 13:41

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0035_ride_destination_location_ride_start_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vias_locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326), blank=True, null=True, size=None),
        ),
    ]
