# Generated by Django 5.2.16 on 2026-09-28 22:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0036_ride_vias_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
