# Generated by Django 5.2.16 on 2026-09-28 22:32

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0037_alter_ride_destination_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vias_locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326), blank=True, null=True, size=None),
        ),
    ]
