# Generated by Django 5.2.16 on 2026-10-02 19:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0038_alter_ride_vias_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='vias',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='vias_json',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='vias_locations',
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('via_json', models.JSONField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='via_points', to='test_app.ride')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
