# Generated by Django 5.2.16 on 2026-10-04 11:54

import uuid
from django.db import migrations, models

from carpool.uuid_migration import converter


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_uuid_primary_keys'),
        ('test_app', '0039_via'),
    ]

    # Primary keys change from sequential integers to random UUIDs. The
    # database is converted by carpool.uuid_migration, which keeps all existing
    # rows and the references between them. This cannot be reversed.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(converter("test_app_ride", "test_app_via", "test_app_address")),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='address',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='ride',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='via',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
