# Generated by Django 5.2.16 on 2026-10-09 18:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0040_uuid_primary_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=3067),
        ),
    ]
