# Generated by Django 6.0.5 on 2026-06-03 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_app', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(upload_to='static/images/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.address')),
            ],
        ),
    ]
