# Generated by Django 6.0.5 on 2026-06-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    # This used to repeat the CreateModel from 0001_initial, which made it
    # impossible to create a database from scratch. It is kept (empty) because
    # existing databases have it recorded as applied.
    operations = []
