# Generated by Django 6.0.5 on 2026-06-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address'),
        ('test_app', '0002_alter_recurring_trip_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recurring_trips',
            field=models.ManyToManyField(blank=True, null=True, to='test_app.recurring_trip'),
        ),
    ]
