# Generated by Django 5.2.16 on 2026-07-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recurring_trips',
            new_name='rides',
        ),
    ]
