# Generated by Django 5.2.16 on 2026-10-04 11:36

from django.db import migrations


def copy_rides_to_passengers(apps, schema_editor):
    # User.rides duplicated Ride.passenger. Copy over any rows that only exist
    # in User.rides before it is removed.
    User = apps.get_model("accounts", "User")
    Ride = apps.get_model("test_app", "Ride")
    UserRides = User.rides.through
    Passenger = Ride.passenger.through

    Passenger.objects.bulk_create(
        [
            Passenger(ride_id=row.ride_id, user_id=row.user_id)
            for row in UserRides.objects.all()
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_pfp'),
        ('test_app', '0039_via'),
    ]

    operations = [
        migrations.RunPython(copy_rides_to_passengers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='rides',
        ),
    ]
