# Generated by Django 5.2.16 on 2026-10-04 11:54

import uuid
from django.db import migrations, models

from carpool.uuid_migration import converter


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_user_rides'),
    ]

    # Primary keys change from sequential integers to random UUIDs. The
    # database is converted by carpool.uuid_migration, which keeps all existing
    # rows and the references between them. This cannot be reversed.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(converter("accounts_user")),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        # Sessions store the old integer user ids, which can no longer be
        # read, so everyone has to log in again. (On a new database the
        # session table does not exist yet.)
        migrations.RunSQL(
            """
            DO $$ BEGIN
                IF to_regclass('django_session') IS NOT NULL THEN
                    DELETE FROM django_session;
                END IF;
            END $$;
            """,
            migrations.RunSQL.noop,
        ),
    ]
