name: Deploy Django backend api to Server

on:
  push:
    branches: [testing]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin testing
          source env/bin/activate
          pip install -r api/requirements.txt
          python manage.py makemigrations test_app accounts
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
          sudo systemctl restart django_ride
        EOF
